version: "3.8"
services:
  qbittorrent:
    image: "linuxserver/qbittorrent:latest"
    container_name: "qbittorrent"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "WEBUI_PORT=${PORT}"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${DOWNLOADS}:/downloads"
    ports:
      - "${PORT}:${PORT}"
      - "6881:6881"
      - "6881:6881/udp"
    restart: "unless-stopped"
