version: "3.3"
services:
  dockerproxy:
    image: "ghcr.io/tecnativa/docker-socket-proxy:0.3.0"
    container_name: "dockerproxy"
    environment:
      - "CONTAINERS=${CONTAINERS}"
      - "SERVICES=${SERVICES}"
      - "TASKS=${TASKS}"
      - "POST=${POST}"
    ports:
      - "${PORT}:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "unless-stopped"
