version: "3.8"
services:
   vaultwarden:
    image: "vaultwarden/server:1.33.2"
    container_name: "vaultwarden"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}"
#      - "SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}"
#      - "ADMIN_TOKEN=${ADMIN_TOKEN}"
#      - "SMTP_HOST=${SMTP_HOST}"
#      - "SMTP_FROM=${SMTP_FROM}"
#      - "SMTP_PORT=${SMTP_PORT}"
#      - "SMTP_SECURITY=starttls"
#      - "SMTP_USERNAME=${SMTP_USERNAME}"
#      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "LOG_FILE=/data/vaultwarden.log"
    volumes:
      - "${DATA_PATH}:/data/"
    ports:
      - "${PORT}:80"
    restart: "unless-stopped"
