version: "3.3"
services:
  dockerproxy:
    image: "tecnativa/docker-socket-proxy:0.3.0"
    container_name: "dockerproxy"
    environment:
      - "CONTAINERS=${CONTAINERS}" # Allow access to viewing containers
      - "SERVICES=${SERVICES}" # Allow access to viewing services (necessary when using Docker Swarm)
      - "TASKS=${TASKS}" # Allow access to viewing tasks (necessary when using Docker Swarm)
      - "POST=${POST}" # Disallow any POST operations (effectively read-only)
    ports:
      - "${PROXY_PORT}:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "unless-stopped"

  homepage:
    image: "gethomepage/homepage:v1.2.0"
    container_name: "homepage"
    environment:
      - "HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    volumes:
      - "${CONFIG_PATH}:/app/config"
      - "${IMAGES_PATH}:/app/public/images"
    ports:
      - "${PORT}:3000"
    restart: "unless-stopped"
