version: "3.3"
services:
  dockerproxy:
    image: "ghcr.io/tecnativa/docker-socket-proxy:0.1.2"
    container_name: "dockerproxy"
    environment:
      - "CONTAINERS=${CONTAINERS}"
      - "SERVICES=${SERVICES}"
      - "TASKS=${TASKS}"
      - "POST=${POST}"
    ports:
      - "${PROXY_PORT}:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "unless-stopped"

  homepage:
    image: "ghcr.io/gethomepage/homepage:v0.10.9"
    container_name: "homepage"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    volumes:
      - "${CONFIG_PATH}:/app/config"
      - "${IMAGES_PATH}:/app/public/images"
    ports:
      - "${PORT}:3000"
    restart: "unless-stopped"
