version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.102.3
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${PHOTOS_PATH_1}:/usr/src/app/external/${USER_1}/photos
      - ${VIDEOS_PATH_1}:/usr/src/app/external/${USER_1}/videos
      - ${PHOTOS_PATH_2}:/usr/src/app/external/${USER_2}/photos
      - ${VIDEOS_PATH_2}:/usr/src/app/external/${USER_2}/videos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../stack.env
    ports:
      - ${SERVER_PORT}:3001
    depends_on:
      - immich-redis
      - immich-postgres
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.102.3
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${PHOTOS_PATH_1}:/usr/src/app/external/${USER_1}/photos
      - ${VIDEOS_PATH_1}:/usr/src/app/external/${USER_1}/videos
      - ${PHOTOS_PATH_2}:/usr/src/app/external/${USER_2}/photos
      - ${VIDEOS_PATH_2}:/usr/src/app/external/${USER_2}/videos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../stack.env
    depends_on:
      - immich-redis
      - immich-postgres
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.131.2
    volumes:
      - ${CACHE_PATH}:/cache
    env_file:
      - ../stack.env
    restart: unless-stopped

  immich-redis:
    container_name: immich_redis
    image: 	redis:7.2.4
    restart: unless-stopped

  immich-postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg15-v0.2.1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
