version: "3.8"
services:
  nginx-reverse-proxy:
    image: "nginx:1.28.0"
    container_name: "nginx-reverse-proxy"
    volumes:
      - "${CONF_PATH}:/etc/nginx/nginx.conf"
      - "${PROXY_PATH}:/etc/nginx/conf.d"
      - "${LOG_PATH}:/var/log/nginx"
      - "${LETSENCRYPT_PATH}:/letsencrypt"

    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
    restart: "unless-stopped"
