version: "3.8"
services:
  stirling-pdf:
    image: "frooodle/s-pdf:latest-fat"
    container_name: "stirling-pdf"
    environment:
      - "DOCKER_ENABLE_SECURITY=${DOCKER_ENABLE_SECURITY}"
      - "SECURITY_ENABLELOGIN=${SECURITY_ENABLELOGIN}"
      - "LANGS=${LANGS}"
    ports:
      - "${PORT}:8080"
    volumes:
      - "${TRAINIG_DATA}:/usr/share/tessdata" #Required for extra OCR languages
      - "${CONFIG_PATH}:/configs"
      - "${CUSTOM_FILES}:/customFiles/"
      - "${LOGS}:/logs/"
      - "${PIPELINE}:/pipeline/"
    restart: "unless-stopped"
