version: "3.8"
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:latest"
    container_name: "uptime-kuma"
    volumes:
      - "${CONFIG_PATH}:/app/data"
    ports:
      - "${PORT}:3001"
    restart: "unless-stopped"
