version: "3.8"
services:
  minio:
    image: "minio/minio:latest"
    container_name: "minio"
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
      - "MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}"
      - "MINIO_SERVER_URL=${MINIO_SERVER_URL}"
    command: server --console-address ":9001" /data
    volumes:
      - "${DATA_PATH}:/data"
    ports:
      - "${PORT1}:9000"
      - "${PORT2}:9001"
    restart: "unless-stopped"
